[package]
name = "usage_examples"
version = "0.1.0"
edition = "2024"

[dependencies]
mycellium_computing = { path = "../core_impl" }
dust_dds = "0.13.0"
tokio = {version = "1.48.0", features = ["full"]}
