[package]
name = "mycellium_computing"
version = "0.1.0"
edition = "2024"

[dependencies]
dust_dds = "0.13.0"
mycellium_computing_macros = { path = "../macros" }
rxrust = "0.15.0"
async-trait = "0.1.89"
tokio = { version = "1.48.0", features = ["full"] }
